// Mocks generated by Mockito 5.0.10 from annotations
// in meal_planner/test/calendar/pages/meal_list/selection/meal_list_selection_page_test.dart.
// Do not manually edit this file.

import 'package:meal_planner/calendar/pages/meal_list/selection/meal_list_api.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [MealListApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealListApi extends _i1.Mock implements _i2.MealListApi {
  MockMealListApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> fetchMealList() =>
      (super.noSuchMethod(Invocation.method(#fetchMealList, []),
          returnValue: <String>[]) as List<String>);
}
