// Mocks generated by Mockito 5.0.10 from annotations
// in meal_planner/test/calendar/calendar_bloc_test.dart.
// Do not manually edit this file.

import 'package:meal_planner/calendar/utils/calendar.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeDateTime extends _i1.Fake implements DateTime {
  @override
  String toString() => super.toString();
}

/// A class which mocks [Calendar].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendar extends _i1.Mock implements _i2.Calendar {
  MockCalendar() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime getToday() => (super.noSuchMethod(Invocation.method(#getToday, []),
      returnValue: _FakeDateTime()) as DateTime);
  @override
  List<DateTime> getCurrentWeek() =>
      (super.noSuchMethod(Invocation.method(#getCurrentWeek, []),
          returnValue: <DateTime>[]) as List<DateTime>);
}
